api_version = "v2.3"
ACTIVE = "Active"
INACTIVE = 'Inactive'
BASE_URL = "hcare.herokuapp.com"
PER_PAGE = "10"
RADIUS = 10

FETCH_SUCCESS_CODE = 200
CREATE_SUCCESS_CODE = 201
ACCEPTED_SUCCESS_CODE = 202
UNAUTHORIZE_ACCESS_CODE = 401
NOT_FOUND_CODE = 404
UNPROCESSABLE_ENTITY_CODE = 422
